This notebook illustrates some examples observed (not exhaustive) from the DataCamp practices, and some other examples.


- https://practice.datacamp.com/p/5
- https://practice.datacamp.com/p/16


### Some Pandas Methods/Attributes


- df.head()
- df.tail()
- df.info()
- df.shape


In [31]:
import pandas as pd
import numpy as np

#### Numpy Logical Functions


In [32]:
x = np.array([9, 5])
y = np.array([16, 12])

np.logical_or(x < 5, y > 15)

array([ True, False])

In [33]:
x < 5

array([False, False])

In [34]:
y > 15

array([ True, False])

In [35]:
# Python's bitwise logic operators
(x < 5) | (y > 15)

array([ True, False])

#### pandas.DataFrame.to_numpy


In [36]:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html
# DataFrame.to_numpy(dtype=None, copy=False, na_value=<no_default>)[source]

df = pd.DataFrame({"A": [1, 2], "B": [3.0, 4.5]})
arr = df.to_numpy()
arr[0, 1] = 100
print(arr)
display(df)

[[  1.  100. ]
 [  2.    4.5]]


A    B
0  1  3.0
1  2  4.5

In [37]:
df = pd.DataFrame({"A": [1, 2], "B": [3.0, 4.5]})
arr = df.to_numpy(copy=True)
arr[0, 1] = 100
print(arr)
display(df)

[[  1.  100. ]
 [  2.    4.5]]


A    B
0  1  3.0
1  2  4.5

In [38]:
# note that the numpy array still references the dataframe
# this behavior is not guaranteed according to the docs
df = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
arr = df.to_numpy()
arr[0, 1] = 100
print(arr)
display(df)

[[  1 100]
 [  2   4]]


A    B
0  1  100
1  2    4

In [39]:
# make an explicit copy
df = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
arr = df.to_numpy(copy=True)  # Using this would be more explicitly declared.
arr[0, 1] = 100
print(arr)
display(df)

[[  1 100]
 [  2   4]]


A  B
0  1  3
1  2  4

In [40]:
df = pd.DataFrame({"A": [1, 2], "B": [3.0, 4.5]})
arr = df.to_numpy()
np.shares_memory(arr, df.values)

False

In [41]:
df = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
arr = df.to_numpy()
np.shares_memory(arr, df.values)

True

#### .copy()


In [42]:
arr1 = arr.copy()
arr1

array([[1, 3],
       [2, 4]])

In [43]:
arr[0, 1] = 33
print(arr)
print(arr1)

[[ 1 33]
 [ 2  4]]
[[1 3]
 [2 4]]


In [44]:
df = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
df1 = df.copy()
df1

A  B
0  1  3
1  2  4

In [45]:
df.iloc[0, 1] = 33
display(df)
display(df1)

A   B
0  1  33
1  2   4

A  B
0  1  3
1  2  4

#### Pandas filtering and Dataframe creation


In [46]:
# example dictionary
my_dict = {
    "course": ["dv", "ds", "de", "de"],
    "level": ["beginner", "intermediate", "intermediate", "advanced"],
    "lesson": [5, 10, 15, 20],
}

In [47]:
datacamp = pd.DataFrame(
    my_dict
)  # question is asking which Pandas function to use - use pd.DataFrame function
datacamp

course         level  lesson
0     dv      beginner       5
1     ds  intermediate      10
2     de  intermediate      15
3     de      advanced      20

In [48]:
datacamp

course         level  lesson
0     dv      beginner       5
1     ds  intermediate      10
2     de  intermediate      15
3     de      advanced      20

In [49]:
datacamp[(datacamp["course"] == "ds")]

course         level  lesson
1     ds  intermediate      10

In [50]:
datacamp[(datacamp["course"] == "ds") | (datacamp["course"] == "de")]

course         level  lesson
1     ds  intermediate      10
2     de  intermediate      15
3     de      advanced      20

In [51]:
# & is evaluated first before |
datacamp[
    (datacamp["course"] == "ds")
    | (datacamp["course"] == "de") & (datacamp["lesson"] >= 15)
]

course         level  lesson
1     ds  intermediate      10
2     de  intermediate      15
3     de      advanced      20

In [52]:
datacamp[
    ((datacamp["course"] == "ds") | (datacamp["course"] == "de"))
    & (datacamp["lesson"] >= 15)
]

course         level  lesson
2     de  intermediate      15
3     de      advanced      20

In [53]:
keys = ["a", "b", "c"]
values = [[1, 2, 3], [11, 22, 33], [10, 20, 30]]

# zip to combine keys and values into a tuple
# Constructing a dictionary from the zipped data
zipped = zip(keys, values)
data = dict(zipped)

data

{'a': [1, 2, 3], 'b': [11, 22, 33], 'c': [10, 20, 30]}

In [54]:
pd.DataFrame(data)

a   b   c
0  1  11  10
1  2  22  20
2  3  33  30

In [55]:
keys = ["a", "b", "c"]
values = [[1, 2, 3], [11, 22, 33], [10, 20, 30]]

# zip to combine keys and values into a tuple
# Constructing a list from the zipped data
list(zip(keys, values))

[('a', [1, 2, 3]), ('b', [11, 22, 33]), ('c', [10, 20, 30])]

In [56]:
pd.DataFrame(list(zip(keys, values)))

0             1
0  a     [1, 2, 3]
1  b  [11, 22, 33]
2  c  [10, 20, 30]

#### Pandas Dataframe Iterrows


- The iterrows() method generates an iterator object of the DataFrame, allowing us to iterate each row in the DataFrame.
- Each iteration produces an index object and a row object (a Pandas Series object).


In [57]:
import pandas as pd

data = {"firstname": ["Sally", "Mary", "John"], "age": [50, 40, 30]}

df = pd.DataFrame(data)
df

firstname  age
0     Sally   50
1      Mary   40
2      John   30

In [58]:
for index, row in df.iterrows():
    print(f"This is the index: {index}")
    print(f"This is the row: {row}")

This is the index: 0
This is the row: firstname    Sally
age             50
Name: 0, dtype: object
This is the index: 1
This is the row: firstname    Mary
age            40
Name: 1, dtype: object
This is the index: 2
This is the row: firstname    John
age            30
Name: 2, dtype: object


In [59]:
for index, row in df.iterrows():
    print(row["firstname"])

Sally
Mary
John


In [ ]:
# There will be a TypeError if we do this.
# Because iterrows is a generator yielding a tuple of (index, row)
for row in df.iterrows():
    print(row["firstname"])

TypeError: tuple indices must be integers or slices, not str

#### Use of loc and iloc


In [ ]:
dict = {
    "country": ["Brazil", "Russia", "India", "China", "South Africa"],
    "capital": ["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria"],
    "area": [8.516, 17.10, 3.286, 9.597, 1.221],
    "population": [200.4, 143.5, 1252, 1357, 52.98],
}

brics = pd.DataFrame(dict)
brics

country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Delhi   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98

In [62]:
brics.values  # return array representation

array([['Brazil', 'Brasilia', 8.516, 200.4],
       ['Russia', 'Moscow', 17.1, 143.5],
       ['India', 'New Delhi', 3.286, 1252.0],
       ['China', 'Beijing', 9.597, 1357.0],
       ['South Africa', 'Pretoria', 1.221, 52.98]], dtype=object)

In [63]:
brics.shape

(5, 4)

In [64]:
brics["country"]

0          Brazil
1          Russia
2           India
3           China
4    South Africa
Name: country, dtype: object

In [65]:
brics[["country"]]

country
0        Brazil
1        Russia
2         India
3         China
4  South Africa

In [66]:
brics[["country", "area"]]

country    area
0        Brazil   8.516
1        Russia  17.100
2         India   3.286
3         China   9.597
4  South Africa   1.221

In [67]:
brics.loc[:, "country"]

0          Brazil
1          Russia
2           India
3           China
4    South Africa
Name: country, dtype: object

In [68]:
brics.loc[:, ["country"]]

country
0        Brazil
1        Russia
2         India
3         China
4  South Africa

In [69]:
brics.loc[[0, 2], ["country", "area"]]

country   area
0  Brazil  8.516
2   India  3.286

In [70]:
# SyntaxError: invalid syntax
brics.loc[[0:2], ['country', 'area']]

SyntaxError: invalid syntax (3216144531.py, line 2)

In [72]:
brics.loc[0:2, ["country", "area"]]

country    area
0  Brazil   8.516
1  Russia  17.100
2   India   3.286

In [73]:
brics.iloc[:, 0]

0          Brazil
1          Russia
2           India
3           China
4    South Africa
Name: country, dtype: object

In [74]:
brics.iloc[:, [0]]

country
0        Brazil
1        Russia
2         India
3         China
4  South Africa

In [75]:
brics.iloc[1:3, 0:2]

country    capital
1  Russia     Moscow
2   India  New Delhi

#### Quantiles


https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.quantile.html


In [76]:
brics["area"].quantile([0.1, 0.5, 0.9])  # 10%, 50%, 90%

0.1     2.0470
0.5     8.5160
0.9    14.0988
Name: area, dtype: float64

#### Reindex


In [77]:
data = {"age": [50, 40, 30, 40], "qualified": [True, False, False, False]}

df = pd.DataFrame(data)
df

age  qualified
0   50       True
1   40      False
2   30      False
3   40      False

- https://www.w3schools.com/python/pandas/ref_df_reindex.asp
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reindex.html


In [78]:
import pandas as pd

data = {"age": [50, 40, 30, 40], "qualified": [True, False, False, False]}

idx = ["Sally", "Mary", "John", "Monica"]

df = pd.DataFrame(data, index=idx)
df

age  qualified
Sally    50       True
Mary     40      False
John     30      False
Monica   40      False

In [79]:
# Note: The reindex method does NOT make changes to the original DataFrame object.
newidx = ["Robert", "Cindy", "John", "Monica"]
df.reindex(newidx)

age qualified
Robert   NaN       NaN
Cindy    NaN       NaN
John    30.0     False
Monica  40.0     False

In [80]:
# Note: The reindex method does NOT make changes to the original DataFrame object.
df

age  qualified
Sally    50       True
Mary     40      False
John     30      False
Monica   40      False

In [81]:
# Note:The values are set to NaN if the new index is not the same as the old index.

newidx = ["Robert", "Cindy", "John", "Monica"]

newdf = df.reindex(newidx)
newdf

age qualified
Robert   NaN       NaN
Cindy    NaN       NaN
John    30.0     False
Monica  40.0     False

In [82]:
newidx = ["Robert", "Cindy", "John", "Monica"]

newdf = df.reindex(newidx, fill_value="missing")
newdf

age qualified
Robert  missing   missing
Cindy   missing   missing
John         30     False
Monica       40     False